name: chattrix_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  go_router: ^16.2.4
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.3.2
  flutter_secure_storage: ^10.0.0-beta.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  dio: ^5.9.0
  web_socket_channel: ^3.0.1
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  cloudinary_public: ^0.23.1
  http_parser: ^4.1.2
  record: ^6.1.2
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  video_player: ^2.10.0
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_emoji: ^2.5.1
  visibility_detector: ^0.4.0+2
  intl: ^0.19.0
  logger: ^2.6.2
  agora_rtc_engine: ^6.4.0
  wakelock_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  faker: ^2.1.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Load .env file
  assets:
    - .env
